### ISSUE TITLE
Add an icon

### ISSUE THREAD

**Issue by probonopd** [PJK136/TilingGenerator#1]
AppImage generation is failing because there is no icon. Add `Icon=tilinggenerator` to the desktop file, and have `make install` add the icon to `<location>/usr/share/icons/hicolor/512x512/apps/tilinggenerator.png`.

**Comment by PJK136** [comment]
It fixed, thanks !

At the same time, I found your answers here : https://github.com/AppImage/AppImageKit/issues/954

It's an old project and at that time, I didnt design any icon for it. :disappointed: I just wanted to try using AppImage.
